from rummycup import *

##b = board()	
##b.read("board.txt")
###hand.read("hand.txt")
##print ("SOL")
##print (b.validate(1000))
##print ("---b---")
##b.solutiontostr()
##printstonearray(b.stones)
##print ("------")
##print (b.validate(1000))
##print ("------")
##b.solutiontostr()
##printstonearray(b.stones)
##print ("------")
##print (b.validate(1000))
##print ("---b---")
##b.solutiontostr()
##printstonearray(b.stones)
##print ("------")
##print (b.validate(100))
##print ("---b---")
##b.solutiontostr()
##print ("------")
##print ("RES")
##print (str(len(b.residuum)))
##printstonearray(b.residuum)


p1 = player("Sokrates")
p2 = player("Platon")
p3 = player("Aristoteles")
b = board()
g = game([p1,p2,p3],b)
g.printoutboard()
g.dealout(14)
g.printouthands()
for i in range(0,30):
    g.maketurn(0)
    print("-------------------")
    g.board.solutiontostr()
    print("-------------------")
    g.printouthands()
    print("####################")
    g.maketurn(1)
    print("-------------------")
    g.board.solutiontostr()
    print("-------------------")
    g.printouthands()
    print("####################")
    g.maketurn(2)
    print("-------------------")
    g.board.solutiontostr()
    print("-------------------")
    g.printouthands()
    print("####################")
